version: '3.8'

services:
  mongo:
    image: mongo:latest         
    container_name: nest-mongo-db
    restart: unless-stopped     
    
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
  
    ports:
      - "27017:27017"
      
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local