version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: nest-mongo-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: ["--replSet", "rs0"]
volumes:
  mongo-data:
    driver: local